export const SPORT_TYPES = [
    'BASKETBOLS',
    'HOKEJS',
    'MOTOSPORTS',
    'AUTOSPORTS',
    'FLORBOLS',
    'FUTBOLS',
    'HANDBOLS',
    'VOLEJBOLS',
    'PLUDMALES VOLEJBOLS',
    'SKRIEŠANA',
    'UZŅĒMUMI',
    'MAMANET',
    'DISKU GOLFS',
    'GOLFS',
    'E-SPORTS',
    'VIEGATLĒTIKA',
    'CITS SPORTS',
    'PELDĒŠANA',
    'MAKŠĶERĒŠANA',
    'ŠAUTRIŅAS',
    'BILJARDS',
    'MILITĀRS KLIENTS',
    'FANU APĢĒRBS',
    'INDIVIDUĀLS KLIENTS',
    'BOULINGS'
];
